vite.config.ts

* https://app.asana.com/0/1207235467645387/1207247210503273/f
* Set the base path in `vite.config.js` in order to deploy this repo to Github Pages. (https://vitejs.dev/guide/static-deploy#github-pages)

config: Add base path the deploy to Github Pages

---

src/components/ChatIcon/ChatIcon.module.css
src/components/ChatWindow/ChatWindow.module.css
src/components/ChatWindow/ChatWindow.tsx

[Asana: [FE] Update chatbot's interface (3)](https://app.asana.com/0/1207341870835443/1207326494446496/f)
style: here are things that I've done:
- Make yellow glowing around ChatIcon
- Change font size and color of placeholder's text in chat input
- Change size of chat window, chat header, chat input
- Increase margin between message bubbles
- Make text in chat header bold

style: re-style on ChatWindow to match new design changes

---

src/tests/open-api/endpoint.http

The mock endpoint does not answer the question
update the endpoint that works with LLM

add endpoint that works with LLM

---

src/main.tsx

Fix import errors in `main.tsx` file.

config: Fix error in main.tsx

---

package.json
pnpm-lock.yaml
src/components/ChatIcon/ChatIcon.module.css
src/components/ChatWindow/ChatWindow.module.css
src/components/ChatWindow/ChatWindow.tsx
src/index.css
src/main.tsx
vite.config.ts

[As a customer I want to embeded the code to my website, So I can use the bot (4)](https://app.asana.com/0/1207458980633630/1207359608169810/f)
- Install cssInjectedByJsPlugin package to combine CSS into single JS file
- Instead of create #root, using 'div' as a container for project
- Using `rem` unit for all properties in CSS
- Apply `transparent` color on body so that client's website can display proper `background-color`
Note: All links below are used for demonstration only
- Assuming this website is used for marketing Chatbot project: https://drycleaning-aichatbot.netlify.app/
- This path contains bundle file from Chatbot after running `pnpm run build`: https://drycleaning-aichatbot.netlify.app/widget/chat-widget.iife.js
- Client inject this script to their website to use Chatbot: …

feat: bundle project

---

src/components/ChatWindow/ChatWindow.module.css
src/components/ChatWindow/ChatWindow.tsx
src/constant/message.ts
src/types/message.ts
src/utils/useChatHandler.ts

- [Convert options into button/hyperlink (whatever is easier) to invite User to click to start a conversation](https://app.asana.com/0/1207458980633630/1207405848434115/f)
(Welcome messages when user open ChatWindow have options to click)
1. Update `DEFAULT_MSG` to have `options` object
2. Update `message.ts` to have `options` type
3. in ChatWindow.tsx, render addition `options` as button
4. Handle when user click options (similar action to `handleSendClick`, display message to UI, send data to server, display response to UI...)
5. Refactor `try...catch...` block in `handleSendClick` and `handleOptionsClick` into `sendMessageToServerAndDisplay` function
6. Create custom hook `useChatHandler` to handle error, loading, useHistory, sendMessageToServerAndDisplay.
7. CSS: Style for alert …

feat: convert options from DEFAULT_MSG into clickable button

---

src/components/ChatWindow/ChatWindow.module.css
src/components/ChatWindow/ChatWindow.tsx

- [[FE] Fix bugs from user feedbacks](https://app.asana.com/0/1207458980633630/1207578051226894/f)
Change clickable options' color to #0797FF
Change bot's name to Laundry Services Chatbot

style: update style for chatWindow

---

.github/workflows/CICD_developbranch

the name of pipeline is wrong
Fix for wrong pipeline name

fix for wrong pipeline name

---

src/components/ChatWindow/ChatWindow.module.css
src/components/ChatWindow/ChatWindow.tsx
src/constant/message.ts

- [[FE] Disable chat when waiting for response](https://app.asana.com/0/1207458980633630/1207622440482844/f)
- Separate options in each `Button` component.
- Add `disabled` state in options and input chat when waiting for response

feat: disable state for options and input chat when waiting for response

---

package.json
pnpm-lock.yaml

* https://app.asana.com/0/1207458980633630/1207590834247080/f

feat: Generate UUID for ChatSessionId & fix typo

---

pnpm-lock.yaml

merge: Sync `main` into `develop` part 2

---

src/components/ChatIcon/ChatIcon.module.css
src/components/ChatWindow/ChatWindow.module.css
src/components/ChatWindow/ChatWindow.tsx
src/constant/message.ts
src/main.tsx

- [[FE] UI Update: Change the click button layout like this](https://app.asana.com/0/1207500863946452/1207740005929044/f)
- [[FE] UI Update: Chatbot title. Font and size. Please refer to Figma for the details](https://app.asana.com/0/1207500863946452/1207740005929040/f)
- [[FE] UI Update: Icon colors and animation. Please refer to Figma for the details](https://app.asana.com/0/1207500863946452/1207740005929036/f)
- [[FE] UI update: Size and color of chatbox. Please refer to Figma for the details](https://app.asana.com/0/1207500863946452/1207740005929033/f)
- Update default font-size for paragraph and heading in `main.tsx`

Vu UI update

---

src/components/ChatWindow/ChatWindow.module.css

- [[FE] Remove gray border of text input](https://app.asana.com/0/1207801502231764/1207858870630141/f)

fix: remove gray border around text input in ChatWindow

---

pnpm-lock.yaml
src/components/ChatWindow/ChatWindow.module.css
src/components/ChatWindow/ChatWindow.tsx
src/components/ConfirmationModal/ConfirmationModal.module.css
src/components/ConfirmationModal/ConfirmationModal.tsx

1. Target input using styles API to remove border

fix: Update UI

---

src/components/ConfirmationModal/ConfirmationModal.module.css
src/components/ConfirmationModal/ConfirmationModal.tsx

The Modal was pushed over by the padding.
Fixed the padding inline of the modal.

fix: Modal responsive

---

index.html
src/components/ChatIcon/ChatIcon.module.css
src/components/ChatWindow/ChatWindow.module.css
src/components/SendBtn/SendBtn.module.css
src/constant/message.ts

- [[P1] Make the Chatbot looks good in all mobile and all screen sizes and different browsers - Chrome and Safari (4h)](https://app.asana.com/0/1208138780222980/1207969749391963/f)
- [[FE] Fix typo in 'alternations' to 'alterations'](https://app.asana.com/0/1208138780222980/1207944912776349/f)
- [[FE] fix bugs on iOS](https://app.asana.com/0/1208138780222980/1208241610466037/f)
- for prevent zoom when click on text input on iOS devices, declare `meta` tag in `index.html` and add `-webkit-text-size-adjust: 100%;` in .textInput
- for ChatIcon and ChatWindow, declare `media` query for screen size below 480px. Adjust font size, position,...
- for bug on iOS that cause `sendBtn` to be shifted a little bit to the left, declare new padding on `sendBtn`
- Video demo on mobile, tested on Chrome …

style: update responsive design

---

src/components/ChatIcon/ChatIcon.module.css
src/components/ChatWindow/ChatWindow.module.css
src/components/ChatWindow/ChatWindow.tsx

- [[FE] Add glowing animation to the icon (2h)](https://app.asana.com/0/1208380015791677/1208415325666635/f)
- Add yellow light glowing animation around ChatIcon 
- Change IconX to IconMinus in ChatWindow's header (button to close/minimize ChatWindow)
https://github.com/user-attachments/assets/71a180b9-8696-4e28-bec3-2d5097d216a6

style: glowing icon

---

src/components/ChatWindow/ChatWindow.tsx

fix: remove unused code

---

.github/workflows/CICD_developbranch.yml

Making the .env file readable when the pipeline triggers

Yotlaire new branch

---

.github/workflows/CICD_developbranch.yml
package.json
pnpm-lock.yaml
vite.config.ts

Yotlaire branch

---

pnpm-lock.yaml
src/App.tsx
src/components/ChatBot/ChatBot.tsx
src/components/ChatWindow/ChatWindow.module.css
src/components/ChatWindow/ChatWindow.tsx
src/components/HelperText/HelperText.module.css
src/components/HelperText/HelperText.tsx
src/components/HelperText/index.ts
src/components/PopupMessage/PopupMessage.module.css
src/components/PopupMessage/PopupMessage.tsx
src/components/PopupMessage/index.ts
src/hooks/useChatHistory.ts
src/main.tsx
src/utils/getBotIdFromScripTag.ts

-  [Update text color for the chatbot to #3B3B3B (global)](https://app.asana.com/0/1208530409762007/1208536390834451/f)
- [Implement a pop-up message when the website is opened (global)](https://app.asana.com/0/1208530409762007/1208536390834452/f)
- [Add a permanent message at the top of the bot in size 10 font: "I’m still in training. If you have any concerns about my responses, please email chitananda@careerbliss.academy."](https://app.asana.com/0/1208530409762007/1208536390834453/f)
- In `main.tsx`, update `--mantine-text-color` to `#3B3B3B`
- Create `getBotIdFromScripTag` function to get `botId` from script tag and use it in `ChatBot` and `ChatWindow`
- Create `HelperText.tsx` component, get `helperText` value from `sessionStorage`
- Create `PopupMessage.tsx` component. In `ChatBot`, …

feat: implement helper text and popup message

---

package.json
pnpm-lock.yaml
src/components/ChatWindow/ChatWindow.module.css
src/components/ChatWindow/ChatWindow.tsx

- [[FE] Format the links in bot's response](https://app.asana.com/0/1208530409762007/1208744004642300/f)
- Install [Markdown](https://www.npmjs.com/package/react-markdown?activeTab=readme) library
- In `ChatWindow.tsx`: wrap `msg.message` inside `Markdown` to convert [join-us page](https://careerbliss.academy/join-us) to link
- Update css because Markdown will create margin for paragraph
Before:
After:

feat: format link in bot's response
